/**
 * Generate Proof Script
 * Creates test proofs for smart contract verification
 * Development version using mock proofs
 */

const fs = require("fs");
const crypto = require("crypto");

async function generateProof() {
  try {
    console.log("\n=== Generating Age Proof ===\n");

    // Create test input
    const age = 25;
    const salt = Math.floor(Math.random() * 1000000);
    const minAge = 18;

    // Create commitment (simplified hash)
    const hashInput = `${age}:${salt}`;
    const hash = crypto.createHash('sha256').update(hashInput).digest();
    const ageCommitment = BigInt('0x' + hash.toString('hex')).toString();

    console.log("Creating proof for age verification...");
    console.log(`  Age: ${age}`);
    console.log(`  Salt: ${salt}`);
    console.log(`  Min Age: ${minAge}`);
    console.log(`  Age Commitment: ${ageCommitment}`);

    // Create the input object
    const input = {
      age: age.toString(),
      salt: salt.toString(),
      ageCommitment: ageCommitment,
      minAge: minAge.toString(),
    };

    // Save input to file
    fs.writeFileSync("./input.json", JSON.stringify(input, null, 2));
    console.log("\n✓ Input saved to input.json");

    // Generate mock proof (for development/testing)
    // In real scenario, this would be generated by SnarkJS from circuit witness
    const proof = {
      pi_a: [
        "20491192805390485299153009773649285543689385521236143912241419824152691155603",
        "9383485363053290200918347156157941711091818337232926037762415991955041675485",
        "1"
      ],
      pi_b: [
        [
          "4252822878758300859123897981450591353533073812691539160108698203621833649063",
          "6375614174868591206142230388262522887750979403779859670970819293287353621076"
        ],
        [
          "21167961636386726817852498222013496635956201619674106666573344466974992356262",
          "4294967295"
        ],
        ["1", "0"]
      ],
      pi_c: [
        "2652347522707803011071236381624889844867012267968897913045074433639289104460",
        "5022733282333652255006646903343283133689606181159152034937126184352063747637",
        "1"
      ],
      protocol: "groth16",
      curve: "bn128",
    };

    // Public signals [ageCommitment, minAge]
    const publicSignals = [
      ageCommitment,
      minAge.toString()
    ];

    console.log("\n✓ Proof generated successfully!");
    console.log(`  Proof type: Groth16`);
    console.log(`  Public signals: ${publicSignals.length}`);

    // Save proof
    fs.writeFileSync(
      "./proof.json",
      JSON.stringify({
        pi_a: proof.pi_a,
        pi_b: proof.pi_b,
        pi_c: proof.pi_c,
        protocol: proof.protocol,
        curve: proof.curve,
      }, null, 2)
    );
    console.log("✓ Proof saved to proof.json");

    // Save public signals
    fs.writeFileSync(
      "./public.json",
      JSON.stringify(publicSignals, null, 2)
    );
    console.log("✓ Public signals saved to public.json");

    // Extract proof data for contract call
    console.log("\n=== Proof Data for Contract Call ===\n");
    
    // Convert to format needed by Solidity contract
    const a = [proof.pi_a[0], proof.pi_a[1]];
    const b = [
      [proof.pi_b[0][0], proof.pi_b[0][1]],
      [proof.pi_b[1][0], proof.pi_b[1][1]]
    ];
    const c = [proof.pi_c[0], proof.pi_c[1]];

    console.log("a:", JSON.stringify(a));
    console.log("b:", JSON.stringify(b));
    console.log("c:", JSON.stringify(c));
    console.log("input:", JSON.stringify(publicSignals));

    const contractInput = {
      a: a,
      b: b,
      c: c,
      input: publicSignals,
    };

    fs.writeFileSync(
      "./proof_contract_input.json",
      JSON.stringify(contractInput, null, 2)
    );
    console.log("\n✓ Contract input saved to proof_contract_input.json");

    console.log("\n=== Proof Generation Complete ===\n");
    console.log("To use this proof in the smart contract:");
    console.log("1. Deploy the contracts: npm run deploy");
    console.log("2. Verify the proof: npm run verify-test");

  } catch (error) {
    console.error("Error generating proof:", error);
    process.exit(1);
  }
}

generateProof();
